# Generated by Django 2.1.7 on 2019-08-28 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='Код')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Цена')),
                ('price_SP', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='ЦенаСП')),
                ('amount', models.FloatField(blank=True, null=True, verbose_name='Количество')),
                ('properties_field', models.CharField(blank=True, max_length=255, null=True, verbose_name='Поля свойств')),
                ('purchase', models.FloatField(blank=True, null=True, verbose_name='Совместные покупки')),
                ('unit', models.CharField(blank=True, max_length=15, null=True, verbose_name='Единица измерения')),
                ('picture', models.CharField(blank=True, max_length=50, null=True, verbose_name='Картинка')),
                ('output', models.BooleanField(verbose_name='Выводить на главной')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Level_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_1', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Level_2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_2', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Level_3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_3', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='good',
            name='level_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='input.Level_1', verbose_name='Уровень1'),
        ),
        migrations.AddField(
            model_name='good',
            name='level_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='input.Level_2', verbose_name='Уровень2'),
        ),
        migrations.AddField(
            model_name='good',
            name='level_3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='input.Level_3', verbose_name='Уровень3'),
        ),
    ]
