# Generated by Django 2.1.7 on 2019-08-29 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0003_auto_20190829_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='good',
            name='purchase',
            field=models.IntegerField(blank=True, null=True, verbose_name='Совместные покупки'),
        ),
    ]
